version: '2' 
services:
  namenode:
    image: lrxcywq/hdp-namenode:3.2.1
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
  datanode:
    image: lrxcywq/hdp-datanode:3.2.1
    depends_on: 
      - namenode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075
  spark-master:
    image: lrxcywq/spark-master:3.0.0
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop.env
  spark-worker:
    image: lrxcywq/spark-worker:3.0.0
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081
    env_file:
      - ./hadoop.env
  spark-notebook:
    image: lrxcywq/spark-notebook:3.0.0
    container_name: spark-notebook
    env_file:
      - ./hadoop.env
    ports:
      - 9001:9001
  hue:
    image: lrxcywq/hue:4.7.0
    ports:
      - 8088:8088
    environment:
      - NAMENODE_HOST=namenode
