version: '2'
services:
  spark-master:
    image: lrxcywq/spark-master:3.0.0-hadoop3.2.1
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: lrxcywq/spark-worker:3.0.0-hadoop3.2.1
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
