version: "2.1"

services:
  namenode:
    image: lrxcywq/hdp_namenode:3.2.1
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    healthcheck:
      interval: 5s
      retries: 100 
    networks:
      - spark-net
  datanode:
    image: lrxcywq/hdp_datanode:3.2.1
    container_name: datanode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      namenode:
        condition: service_healthy
    healthcheck:
      interval: 5s
      retries: 100 
    networks:
      - spark-net
  spark-master:
    image: lrxcywq/spark-master:3.0.0
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy
    healthcheck:
      interval: 5s
      retries: 100 
    networks:
      - spark-net
  spark-worker:
    image: lrxcywq/spark-worker:3.0.0
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      spark-master:
        condition: service_healthy
    healthcheck:
      interval: 5s
      retries: 100 
    networks:
      - spark-net
  spark-notebook:
    build: .
    ports:
      - 9001:9001
    depends_on:
      spark-master:
        condition: service_healthy
      namenode:
        condition: service_healthy
    networks:
      - spark-net

networks:
  spark-net:
    external:
      name: spark-net
